name: Dream-Frontend CI/CD

# Trigger workflow only when changes are pushed to or pulled into 'dev' branch
# AND only if the changes affect files inside the 'frontend' folder
on:
  push:
    branches: [dev]
    paths: [frontend/**]
  pull_request:
    branches: [dev]
    paths: [frontend/**]

jobs:
  lint-build-push-to-dockerhub:
    runs-on: ubuntu-latest

    steps:
      #  Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      #  Step 2: Lint the frontend code using ESLint
      # This uses the 'wearerequired/lint-action' GitHub Marketplace Action
      - name: Lint frontend with ESLint
        uses: wearerequired/lint-action@v2
        with:
          eslint: true               # Enable ESLint
          eslint_dir: frontend       # Run ESLint inside the frontend directory
          auto_fix: false            # Only report issues, do not auto-fix them

      # ✅ Step 3: Authenticate to Docker Hub using stored GitHub secrets/variables
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}   # Set as a repository variable
          password: ${{ secrets.DOCKERHUB_TOKEN }}   # Set as a secret

      # ✅ Step 4: Set up Docker Buildx (required for docker/build-push-action)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ✅ Step 5: Build and push the Docker image to Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: aiyus/dream-frontend:${{ github.sha }}   # Tag image with commit SHA
