name: Dream-Frontend CI/CD

# Trigger this workflow on push or pull request to the 'dev' branch
on:
  push:
    branches: [dev]
    paths: [Dream-Vacation-App-main/frontend/**]
  pull_request:
    branches: [dev]
    paths: [Dream-Vacation-App-main/frontend/**]
    
jobs:
  lint-build-push-to-dockerhub:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run ESLint to check for code quality issues in the backend directory
      - name: Lint backend with ESLint
        uses: wearerequired/lint-action@v2
        with:
          eslint: true                 # Enable ESLint
          eslint_dir: Dream-Vacation-App-main/backend         # Target backend directory
          auto_fix: false              # Only report errors, don't try to auto-fix

      # Step 3: Login to Docker Hub using GitHub secrets (Docker credentials)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}   # Username stored in repository variables
          password: ${{ secrets.DOCKERHUB_TOKEN }}   # Token stored securely in secrets

      # Step 4: Set up Docker Buildx (a builder for advanced features like multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 5: Build and push the Docker image to Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: aiyus/dream-backend:${{ github.sha }}   # Image tagged with the commit SHA
